analyzer:
  exclude:
    - build/**

  errors:
    avoid_unnecessary_containers: warning
    await_only_futures: error
    constant_identifier_names: warning
    empty_constructor_bodies: error
    exhaustive_cases: error
    file_names: error
    library_prefixes: error
    missing_required_param: error
    non_constant_identifier_names: warning
    prefer_if_null_operators: error
    prefer_is_not_empty: error
    prefer_null_aware_operators: error
    unnecessary_const: warning
    unnecessary_new: error
    unnecessary_this: error
    unused_field: warning
    prefer_final_locals: warning

linter:
  rules:
    use_super_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    omit_local_variable_types: false
    unawaited_futures: false
    always_use_package_imports: true